### ISSUE TITLE
Item 39, Item 40 

### ISSUE THREAD

**Issue by truehong** [code-chobo-study/effective-java#38]
[Item 39 - 명명 패턴 보다 애너테이션을 사용하라. ](https://github.com/code-chobo-study/effective-java/blob/main/6%EC%9E%A5-%20%EC%97%B4%EA%B1%B0%ED%83%80%EC%9E%85%EA%B3%BC%20%EC%95%A0%EB%84%88%ED%85%8C%EC%9D%B4%EC%85%98/%EC%95%84%EC%9D%B4%ED%85%9C39%20-%20%EB%AA%85%EB%AA%85%ED%8C%A8%ED%84%B4%EB%B3%B4%EB%8B%A4%20%EC%95%A0%EB%84%88%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%84%20%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC.md)
[Item 40 - @Override 애너테이션을 일관되게 사용하라.](https://github.com/code-chobo-study/effective-java/blob/main/6%EC%9E%A5-%20%EC%97%B4%EA%B1%B0%ED%83%80%EC%9E%85%EA%B3%BC%20%EC%95%A0%EB%84%88%ED%85%8C%EC%9D%B4%EC%85%98/%EC%95%84%EC%9D%B4%ED%85%9C40%20-%20%40Override%20%EC%95%A0%EB%84%88%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%84%20%EC%9D%BC%EA%B4%80%EB%90%98%EA%B2%8C%20%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC.md)

 Item 39 는, 애너테이션에 대한 정의와 사용하는 방법 그리고 테스트 도구에서 동작을 확인 하는 코드 예시가 좋았던것 같습니다. 
기본 개념을 함께 알면 좋을 것 같아 아래의 링크 첨부 합니다. 
[애너테이션에 대한 기본 개념](https://blog.advenoh.pe.kr/java/%EC%9E%90%EB%B0%94-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98-%EB%A7%8C%EB%93%A4%EA%B8%B0/)
 
추가로,  

[마커인터페이스 vs 마커 애너테이션](https://dahye-jeong.gitbook.io/java/java/effective_java/2021-06-14-use-marker-interfaces-to-define-types)  
위 링크의 ObjectOutputStream 에서 Serializable 과 같은 마커인터페이스를 활용하는 내용에서 보이는 마커 인터페이스나 애너테이션을 
객체와 결합하여 런타임시 활용하는 패턴을 실무에서 어떻게 적용해 보면 좋을지 고민해 보면 좋을 것 같습니다.
 
Item 40은, 책에서 override 를 의식적으로 사용하라고 나와있지만 최근 IDE 에서는 같은 함수명에 대한 override 애노태이션의 정의가 
강제? 되었기 때문에 핵심 정의만 간단히 보면 좋을것 같습니다.

**Comment by sangyyypark** [comment]
@truehong 님 고생하셨습니다.
 intellij를 통해 인터페이스나 추상클래스를 단축키로 구현하도록하면 자동으로 override애노테이션을 붙여주므로 40장은 가볍게 봐도 되겠군요

39장에서 질문이 있는데
1. 명명패턴이라는것이 메서드명이나 클래스명에 일정한 규칙을 가지도록해서 구분하는 그런 방법일까요???

**Comment by truehong** [comment]
@sangypark0324 
넵 저도 그렇게 이해했습니다. 아래와 같은  예제처럼 사용되었을것 같습니다.
https://yenaworldblog.wordpress.com/2018/05/30/java-reactive-%EC%9B%90%ED%95%98%EB%8A%94-%EC%9D%B4%EB%A6%84%EC%9D%84-%EA%B0%80%EC%A7%84-%ED%95%A8%EC%88%98%EB%A7%8C-%EC%8B%A4%ED%96%89/
