### ISSUE TITLE
[Week2] 아이템12 - toString을 항상 재정의 하라 

### ISSUE THREAD

**Issue by truehong** [code-chobo-study/effective-java#9]
간단하지만 유익했던 내용이었던 것 같습니다.

링크 - https://github.com/code-chobo-study/effective-java/blob/main/2%EC%9E%A5-%EA%B0%9D%EC%B2%B4%20%EC%83%9D%EC%84%B1%EA%B3%BC%20%ED%8C%8C%EA%B4%B4/%EC%95%84%EC%9D%B4%ED%85%9C12-toString%EC%9D%84%20%ED%95%AD%EC%83%81%20%EC%9E%AC%EC%A0%95%EC%9D%98%20%ED%95%98%EB%9D%BC.md

**Comment by junghyun100** [comment]
이슈로 작성하신 줄은 확인을 미처 못했네요.
Object의 toString()은 해시코드로 나타나니, toString을 재정의해서 사용하면 편의성이 올라가겠네요.
Object의 toString()을 이용해 해시코드로 또 다른 어떤 일들을 할 수 있을까요?
혹시 알고계시다면 답글 부탁드립니다~

고생하셨습니다.

**Comment by sangyyypark** [comment]
> bject의 toString()은 해시코

@junghyun100 님 해시코드값 자체로 우리가 뭔가를 직접하는 일은 좋지 않을것 같은데 직접 사용할일은 없지 않을까요???

**Comment by junghyun100** [comment]
아하 그렇군요. @sangypark0324 님 답변주셔서 감사합니다.

**Comment by truehong** [comment]
저도 뭔가 object 의 toString을 hashcode로 나타낸 이유가 따로 있지 않을까 해서 궁금했었는데요.
hashcode를 이용한 equals 가 더 빠르다 라고 밖에 확인을 못했네요.
책 대로 클래스의 모든 필드를 담아 논리적 동등성 비교가 되도록 재정의 하는것이 바람직할 것 같네요.
